season = "2025-2026"

files = [
    "../records/2025-2026/Round1.txt",
    "../records/2025-2026/Round2.txt",
    "../records/2025-2026/Round3.txt",
    "../records/2025-2026/Round4.txt",
    "../records/2025-2026/Round5.txt",
    "../records/2025-2026/Round6.txt"
]

save_to_csv = true
print_to_console = true